name: passbook
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0
  google_fonts: ^1.1.1
  hive: ^1.4.4+1
  hive_flutter: ^0.3.0+2
  path_provider: ^1.6.24
  provider: ^4.3.2+2
  shared_preferences: ^0.5.12+4

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.8.0
  hive_generator: ^0.7.0+2

flutter:

  uses-material-design: true
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
